// default package
// Generated Dec 3, 2018 10:15:22 AM by Hibernate Tools 5.2.3.Final

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer id;
	private Store store;
	private String country;
	private String capital;
	private String address;

	public Address() {
	}

	public Address(Store store, String address) {
		this.store = store;
		this.address = address;
	}

	public Address(Store store, String country, String capital, String address) {
		this.store = store;
		this.country = country;
		this.capital = capital;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
