// default package
// Generated Dec 3, 2018 10:15:22 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productId;
	private String productName;
	private String productCode;
	private double productPrice;
	private Integer branchId;
	private Set categories = new HashSet(0);
	private Set stores = new HashSet(0);

	public Product() {
	}

	public Product(String productName, String productCode, double productPrice) {
		this.productName = productName;
		this.productCode = productCode;
		this.productPrice = productPrice;
	}

	public Product(String productName, String productCode, double productPrice, Integer branchId, Set categories,
			Set stores) {
		this.productName = productName;
		this.productCode = productCode;
		this.productPrice = productPrice;
		this.branchId = branchId;
		this.categories = categories;
		this.stores = stores;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public double getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(double productPrice) {
		this.productPrice = productPrice;
	}

	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

	public Set getStores() {
		return this.stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}

}
