// default package
// Generated Dec 3, 2018 10:15:22 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Integer storeId;
	private String storeName;
	private Set products = new HashSet(0);
	private Set addresses = new HashSet(0);

	public Store() {
	}

	public Store(String storeName) {
		this.storeName = storeName;
	}

	public Store(String storeName, Set products, Set addresses) {
		this.storeName = storeName;
		this.products = products;
		this.addresses = addresses;
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
